// Mocks generated by Mockito 5.2.0 from annotations
// in firstcleanarchi/test/infrastructure/repositories/advicer_repositories_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:firstcleanarchi/domain/enities/advice_entitiy.dart' as _i2;
import 'package:firstcleanarchi/infrastructur/datasources/advicer_remote_datasource.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeAdviceEntitiy_0 extends _i1.Fake implements _i2.AdviceEntitiy {}

/// A class which mocks [AdvicerRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdvicerRemoteDataSource extends _i1.Mock
    implements _i3.AdvicerRemoteDataSource {
  MockAdvicerRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AdviceEntitiy> getRandomAdviceFromApi() => (super.noSuchMethod(
          Invocation.method(#getRandomAdviceFromApi, []),
          returnValue: Future<_i2.AdviceEntitiy>.value(_FakeAdviceEntitiy_0()))
      as _i4.Future<_i2.AdviceEntitiy>);
}
